name: 'Build, Test, Release'

permissions:
  id-token: write  # Required for NPM trusted publishing
  contents: write

on:
  workflow_dispatch:

jobs:
  release-check:
    name: Check if version is published
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          check-latest: true
          cache: 'npm'

      - name: Check if version is published
        id: check
        run: |
          packageName="$( node -e "console.log(require('./package.json').name)" )"
          currentVersion="$( node -e "console.log(require('./package.json').version)" )"
          isPublished="$( npm view "$packageName" versions --json | jq -c --arg cv "$currentVersion" 'any(. == $cv)' )"
          echo "version=$currentVersion" >> "$GITHUB_OUTPUT"
          echo "published=$isPublished" >> "$GITHUB_OUTPUT"
          echo "currentVersion: $currentVersion"
          echo "isPublished: $isPublished"
    outputs:
      published: ${{ steps.check.outputs.published }}
      version: ${{ steps.check.outputs.version }}

  release:
    needs: release-check
    if: ${{ needs.release-check.outputs.published == 'false' }}
    name: 'Build, Test, Publish'
    runs-on: ubuntu-latest
    environment: release
    env:
      PACKAGE_VERSION: ${{ needs.release-check.outputs.version }}
    steps:
      - name: Check out repository ✨
        uses: actions/checkout@v6

      - name: Update apt-get 🚀
        run: sudo apt-get update -qq

      - name: Setup node env 📦
        uses: actions/setup-node@v6
        with:
          node-version: 24
          check-latest: true
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install npm dependencies 🚀
        run: npm ci

      - name: Run tests 🧪
        run: npm test

      - name: Get release type
        id: prepare_release
        run: |
          RELEASE_TYPE="$(node -e "console.log(require('semver').prerelease('${{ needs.release-check.outputs.version }}') ? 'prerelease' : 'regular')")"
          if [[ $RELEASE_TYPE == 'regular' ]]; then
            echo "prerelease=false" >> "$GITHUB_OUTPUT"
          else
            echo "prerelease=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Publish to NPM
        run: |
          npm publish --access public --tag ${{ steps.prepare_release.outputs.prerelease == 'true' && 'next' || 'latest' }}

